### ISSUE TITLE
Control File Configuration

### ISSUE THREAD

**Issue by lambesa** [socrata/datasync#100]
Hello, I am a new user and don't know how to configure a control file. Can I please get an example? 

It says in the Helptext to go to Help>>Control File configuration, but I'm not sure where the "Help" link is?

**Comment by rjmac** [comment]
"Help" is one of the application's menus, but that menu entry will just bring you to [this web page](http://socrata.github.io/datasync/resources/control-config.html), which contains details and examples about the control file.

**Comment by spaceballone** [comment]
We also recently released a new version of DataSync (1.6) which provides a GUI that constructs a control file under the covers.  Hopefully this makes your integration a bit easier
