### ISSUE TITLE
Logging for GIS Jobs

### ISSUE THREAD

**Issue by levyj** [socrata/datasync#167]
I am not seeing logging for GIS jobs, as exists for Standard (tabular) jobs.  Does it work differently or is there none visible to us?

I do see the jobs in https://data.cityofchicago.org/admin/activity_feed and that is of some help but really mostly just shows whether they succeeded at all. Also, that log is not (yet) enabled with many features to find jobs.

I was thinking more of https://data.cityofchicago.org/datasync/id/[4x4]/log/index, https://data.cityofchicago.org/datasync/id/[4x4]/status/index, and the Data Sync Log dataset we specify in the Data Sync preferences.   I use these fairly frequently for Standard jobs but nothing was present for my GIS job.

If logging is not yet implemented, please take this issue as a request to add it.

Thanks!

Jon

CC @tomschenkjr @shua123

**Comment by treycausey** [comment]
Hi Jon, 

Thanks for the question. I'm the new product manager on the publishing team here at Socrata. Unfortunately, GIS jobs will not appear is the DataSync logs as they do not use the same import API as standard jobs. We hope to add additional logging in the future. As GIS jobs are only full replaces for the time being, hopefully failures are not too difficult to diagnose, but if your jobs are failing, a job id is logged to the console by DataSync that you can provide to support.

Trey

**Comment by levyj** [comment]
Thanks, Trey.  That makes sense.  Adding logging would be nice.  Among other things, it is a good record even of successful jobs.  Nonetheless, I get not making the perfect the enemy of the good.  Better to have the GIS job at all and build from there than hold off until everything is ready.

Jon
