### ISSUE TITLE
Test SMTP Settings button gives error illegal address on Windows Server 2012 R2

### ISSUE THREAD

**Issue by kf6ntg** [socrata/datasync#170]
Hello,

I'm running Socrata DataSync 1.8.0 on a freshly built Windows Server 2012 R2 server and the test SMTP button returns the message "illegal address". 

I also have a windows console app that another developer built that can send out email just fine, 
I also have a fresh install of Java 8 SE. Is this the correct version of Java for DataSync?

thanks for you help,
Brian

**Comment by BradleyMcCarty** [comment]
It works, I’ll forward to the team.

Brad McCarty
Programmer Analyst  - IT Applications
Communications and Technology Management
City of Austin
(512) 974-2739 work     (512) 826-3427 cell
Brad.McCarty@austintexas.gov<mailto:Brad.McCarty@austintexas.gov>

**Comment by BradleyMcCarty** [comment]
I deleted a comment that was intended for a differenct issue.

**Comment by kf6ntg** [comment]
The only way I can get "around" the problem is to enter something into the "SMTP Username" field. 
If I leave that blank then the program appears to crash with an error message of "illegal address".

**Comment by urmilan** [comment]
This is fixed in https://github.com/socrata/datasync/releases/tag/1.8.2.
