### ISSUE TITLE
Port jobs in 1.8.1 are not completing

### ISSUE THREAD

**Issue by levyj** [socrata/datasync#174]
I have tried two port jobs with https://github.com/socrata/datasync/releases/tag/1.8.1 and neither completed, despite the source datasets being fairly small:

https://data.cityofchicago.org/d/xzkq-xp2w (32.7K rows) - Ran for almost 30 minutes before I gave up and closed DataSync.

https://data.cityofchicago.org/d/38sz-xyf4 (9 rows, currently private) - Ran for seven minutes before I gave up and closed DataSync.

Separate question but what I was actually trying to figure out with these test jobs: What does this mean?

> Note, new Port Jobs will port derived views as parent datasets.

I am not sure what a derived view or parent dataset is.  I am guessing a derived view may be Related Content / More Views but am not sure.

Thank you.

**Comment by urmilan** [comment]
@levyj Thanks for the report. We're currently investigating some issues processing port jobs on the server side (unrelated to the Datasync client dropped to Releases today). Our engineers are actively investigating, and I'll keep you up to date here.

**Comment by urmilan** [comment]
@levyj This should be resolved - thanks again for reaching out to us.
