### ISSUE TITLE
Feature request: ability to upload many documents as non-data datasets

### ISSUE THREAD

**Issue by marks** [socrata/datasync#88]
Would be awesome if there was a way to point DataSync to a folder and a data portal and it would upload the many documents in that folder as non-data data sets at once. The user would then go to the web portal to fill out the metadata.

@LouisFettet agrees with me. So yeah :)

**Comment by spaceballone** [comment]
This is something that we'll be looking at with the publishing refresh, but likely not something that DataSync itself will do.  Closing the request accordingly.
